#:schema node_modules/wrangler/config-schema.json
name = "sublink-iqoo"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a3b4ecbd9b124639ac3a8d906bd526e5" }
]

[assets]
directory = "./public"
